### ISSUE TITLE
Response body doesn't appear to log correctly in SDKLogger

### ISSUE THREAD

**Issue by zbuchheit** [apimatic/go-core-runtime#93]
**Describe the bug**

**Where did you find this bug?**
 - [ ] ApiError Package 
 - [ ] Https Package
 - [ ] TestHelper Package
 - [ ] Utilities Package
 - [x] Logger Package

**Expected behavior**
I would expect the response body to be correctly logged

**To Reproduce**
Steps to reproduce the bug:

**Code Link**
It appears the issue stems from the below code. Body is type io.ReadCloser so this doesn't work correctly.
https://github.com/apimatic/go-core-runtime/blob/b368c82722db89cc2a58466dd0033083be2caf6b/logger/sdkLogger.go#L121

**Library version number**
For example:  0.1.1

**Environmental details**
For example:
OS: Linux
Runtime version: GO 1.18

**Additional context**

**Comment by haseeb-mhr** [comment]
@zbuchheit Thank you for reporting this issue!
To help us better diagnose the problem, please share sample inputs or code snippets that consistently reproduce the issue. Alternatively, please elaborate on the differences between the expected and actual log outputs you're observing.

**Comment by zbuchheit** [comment]
I don't suspect any use of logging a body here should work. Do you have an example of logging the body of a response successfully? I don't think you can json.Marshal(response.Body); and it work. In my testing, json.Marshal ends up just converting response.Body to be {}

**Comment by zbuchheit** [comment]
great news! Thank you!

**Comment by haseeb-mhr** [comment]
@zbuchheit The changes have been released. Please bump to the latest version to incorporate the fix. Let me know if you encounter any further issues!
